"""Curated quiz catalog: 100 practical questions for each track."""


def _make_questions(section, concepts):
    questions = []
    for number, (concept, prompt, answer, explanation) in enumerate(concepts, 1):
        difficulty = "easy" if number <= 50 else "medium" if number <= 80 else "hard"
        questions.append({
            "section": section,
            "number": number,
            "difficulty": difficulty,
            "title": concept,
            "prompt": prompt,
            "answer": answer,
            "explanation": explanation,
        })
    return questions


PYTHON_CONCEPTS = [
("List comprehension", "Create a list of the squares of even numbers from 0 through 10.", "[n ** 2 for n in range(11) if n % 2 == 0]", "The condition filters before the expression is evaluated."),
("Dictionary counting", "Write an expression that counts each character in the string text using Counter.", "Counter(text)", "collections.Counter maps each hashable item to its frequency."),
("Safe dictionary lookup", "Return the value for key 'timeout', or 30 when it is absent, from settings.", "settings.get('timeout', 30)", "dict.get avoids a KeyError and supplies the default."),
("Tuple unpacking", "Swap variables left and right in one Python statement.", "left, right = right, left", "Tuple packing and unpacking make the swap atomic and readable."),
("Generator expression", "Create a lazy iterator yielding stripped non-empty lines from lines.", "(line.strip() for line in lines if line.strip())", "Parentheses create a generator without materializing a list."),
("Set membership", "Test whether every item in required is present in available.", "set(required) <= set(available)", "Set subset comparison expresses the requirement directly."),
("Slice reversal", "Return a reversed copy of sequence without mutating it.", "sequence[::-1]", "A negative slice step traverses from the end."),
("Keyword-only argument", "Define function connect so timeout must be passed by keyword.", "def connect(host, *, timeout=10):", "Arguments after * are keyword-only."),
("Exception cleanup", "Which construct guarantees a file is closed after use?", "with open(path) as handle:", "A context manager calls close even when the block raises."),
("Dataclass", "Declare a dataclass User with fields name: str and active: bool = True.", "@dataclass\nclass User:\n    name: str\n    active: bool = True", "dataclass generates an initializer and useful representations."),
("Enumerate", "Iterate over values with both zero-based index and value.", "for index, value in enumerate(values):", "enumerate avoids manual index mutation."),
("Zip", "Build a dictionary pairing keys with values.", "dict(zip(keys, values))", "zip aligns elements by position."),
("Any predicate", "Check whether at least one score in scores is below 50.", "any(score < 50 for score in scores)", "any short-circuits on the first true result."),
("All predicate", "Check that every filename ends with .py.", "all(name.endswith('.py') for name in filenames)", "all short-circuits on the first false result."),
("Sorting key", "Sort records by their case-insensitive name field.", "sorted(records, key=lambda record: record['name'].casefold())", "The key function controls comparison without changing records."),
("F-string formatting", "Format price as a dollar amount with two decimal places.", "f'${price:.2f}'", "The format specifier .2f fixes two fractional digits."),
("Immutable default", "Why should a function avoid def add(item, bucket=[])?", "The list is shared across calls; use bucket=None and create it inside.", "Default arguments are evaluated once when the function is defined."),
("Shallow copy", "Make a shallow copy of dictionary config.", "config.copy()", "copy duplicates the mapping but not nested objects."),
("Deep copy", "Copy nested object graph value so later mutations are independent.", "copy.deepcopy(value)", "deepcopy recursively copies reachable objects."),
("Type annotation", "Annotate parse_ids as accepting a string and returning a list of integers.", "def parse_ids(raw: str) -> list[int]:", "Annotations document the callable contract and support tooling."),
("Regex extraction", "Extract the first sequence of digits from text with re.", "re.search(r'\\d+', text)", "The raw string keeps the regex escape readable."),
("JSON serialization", "Convert mapping payload to a JSON string.", "json.dumps(payload)", "dumps serializes a Python value to JSON text."),
("JSON parsing", "Parse JSON text response into a Python value.", "json.loads(response)", "loads parses JSON text; load is for file objects."),
("Path joining", "Build a cross-platform path to data.csv inside root.", "Path(root) / 'data.csv'", "pathlib's slash operator handles platform separators."),
("Virtual environment", "What command creates a virtual environment named .venv?", "python -m venv .venv", "The standard-library venv module creates an isolated environment."),
("Import guard", "Write the conventional guard that calls main only for direct execution.", "if __name__ == '__main__':\n    main()", "Imports should not execute a program's CLI entry point."),
("Context manager protocol", "Which two methods implement a basic context manager?", "__enter__ and __exit__", "The with statement invokes these methods around the block."),
("Iterable protocol", "Which method makes an object usable by iter(obj)?", "__iter__", "iter calls __iter__ to obtain an iterator."),
("Iterator protocol", "Which method returns the next item for an iterator?", "__next__", "It raises StopIteration when exhausted."),
("Property", "Expose method get_email as a read-only attribute email.", "@property\ndef email(self):\n    return self.get_email()", "property presents computed behavior with attribute syntax."),
("Class method", "Which decorator makes a method receive cls instead of self?", "@classmethod", "A class method is bound to the class."),
("Static method", "Which decorator marks a class utility needing neither self nor cls?", "@staticmethod", "A static method is namespaced on the class without implicit binding."),
("Inheritance", "Call a parent implementation of method save from an overriding method.", "super().save()", "super follows the method resolution order."),
("MRO", "What function returns a class's method resolution order?", "ClassName.mro()", "The MRO determines how Python searches base classes."),
("Hashability", "Why can a tuple be a dictionary key while a list cannot?", "A tuple is hashable when its contents are hashable; a list is mutable and unhashable.", "Dictionary keys require a stable hash."),
("Closure", "What does a nested function retain from its enclosing scope?", "A closure retains referenced variables from the enclosing lexical scope.", "Cells preserve those bindings after the outer function returns."),
("Nonlocal", "Which keyword lets a nested function rebind an enclosing variable?", "nonlocal", "nonlocal targets the nearest enclosing function scope."),
("Global", "Which keyword declares assignment should target a module variable?", "global", "global changes name resolution for assignment in a function."),
("Sorting stability", "Does sorted preserve input order for equal keys?", "Yes, Python sorting is stable.", "Equal-key records retain their original relative order."),
("Binary search", "What is the typical time complexity of bisect search in a sorted list?", "O(log n) to locate the insertion point", "Binary search halves the remaining interval each step."),
("Heap", "Which heapq function removes and returns the smallest item?", "heapq.heappop(heap)", "heapq maintains the smallest item at index zero."),
("Deque", "Which collection supports efficient append and removal at both ends?", "collections.deque", "deque operations at either end are O(1)."),
("LRU cache", "Which decorator caches recent function results with a bounded size?", "@functools.lru_cache(maxsize=128)", "It memoizes calls using hashable arguments."),
("Partial", "Create a new function fixing the first argument of pow to 2.", "functools.partial(pow, 2)", "partial pre-fills positional or keyword arguments."),
("Dataclass ordering", "How can a dataclass generate comparison methods?", "Use @dataclass(order=True).", "order=True adds ordering methods based on declared fields."),
("Async function", "Declare an asynchronous function fetch with no parameters.", "async def fetch():", "Calling it returns a coroutine that must be awaited or scheduled."),
("Await", "How do you obtain the result of coroutine work inside async code?", "result = await operation()", "await suspends the current coroutine until completion."),
("Task scheduling", "Schedule coroutine work concurrently on the running asyncio loop.", "asyncio.create_task(coro())", "create_task wraps the coroutine as a scheduled Task."),
("Databases", "Which sqlite3 placeholder style safely binds a user-supplied name?", "connection.execute('SELECT * FROM users WHERE name = ?', (name,))", "Parameter binding separates data from SQL syntax."),
("Logging", "Create a module logger named after the current module.", "logging.getLogger(__name__)", "Named loggers integrate with application logging configuration."),
("Unit assertion", "In pytest, assert result equals 42.", "assert result == 42", "pytest rewrites assertions to provide useful failure details."),
("Mocking", "What unittest.mock object records calls while returning configurable values?", "Mock", "Mock tracks calls and can be configured per test."),
("Complexity", "What is the average lookup complexity of a Python dictionary?", "O(1)", "Hash-table lookup is constant-time on average."),
("Recursion limit", "Which module function reports Python's recursion limit?", "sys.getrecursionlimit()", "The limit prevents unbounded Python stack growth."),
("Garbage collection", "Which module handles cyclic garbage collection?", "gc", "Reference counting plus gc handles cycles in CPython."),
("Descriptor", "Which protocol method controls instance attribute reads?", "__get__", "Descriptors customize attribute access on classes."),
("Decorator", "What does a decorator generally receive and return?", "It receives a callable and returns a callable, often wrapping it.", "Decorators transform behavior without changing call sites."),
("Vectorization", "Why is a generator preferable to a list for one-pass large input?", "It produces values lazily and uses bounded memory.", "Only the current item needs to be held."),
("Pickle warning", "Why should pickle never load data from an untrusted source?", "Unpickling can execute attacker-controlled code.", "Pickle is a serialization protocol, not a safe interchange format."),
("SQL injection", "What is the primary defense against SQL injection in Python DB-API code?", "Use parameterized queries rather than string concatenation.", "The driver escapes bound values as data."),
("Thread safety", "Does a list append operation make a multi-step business invariant thread-safe?", "No; protect the invariant with an appropriate lock or synchronization strategy.", "Atomic individual operations do not make compound workflows atomic."),
("GIL", "What does CPython's GIL limit for CPU-bound threads?", "Only one thread executes Python bytecode at a time in a process.", "Multiprocessing or native code can provide CPU parallelism."),
("Multiprocessing", "Which module provides a process pool for parallel CPU work?", "multiprocessing.Pool", "Separate processes avoid the CPython GIL for Python code."),
("Protocol typing", "Which typing construct describes behavior without requiring inheritance?", "typing.Protocol", "Structural typing accepts objects matching the declared members."),
("Match statement", "Which statement pattern matches structural cases in Python 3.10+?", "match value:\n    case pattern:", "match/case performs structural pattern matching."),
("Walrus operator", "Assign and test input in one while condition.", "while (line := source.readline()):", "The := expression assigns and yields its value."),
("Exception chaining", "Preserve the original exception while raising a domain error.", "raise DomainError('invalid') from exc", "Explicit chaining keeps the causal traceback."),
("Custom exception", "Define InvalidToken as an exception type.", "class InvalidToken(Exception):\n    pass", "Application exceptions should generally derive from Exception."),
("Import cycle", "Name one clean strategy for breaking a circular import.", "Move shared types or functions into a lower-level module.", "A dependency direction prevents modules from importing each other."),
("Resource limits", "What should production code do when parsing untrusted huge input?", "Enforce size, time, and nesting limits before or during parsing.", "Resource bounds reduce denial-of-service risk."),
("Constant time compare", "Which function compares secrets without early-exit timing differences?", "hmac.compare_digest(a, b)", "It is intended for timing-resistant comparison of equal-type values."),
("Password hashing", "Which property must password storage use instead of encryption?", "A slow, salted password hash such as Argon2 or scrypt.", "Passwords should not be recoverable and each salt defeats rainbow tables."),
("JWT validation", "What must a service verify before trusting a JWT claim?", "Signature, algorithm, issuer, audience, expiration, and relevant claims.", "Decoding a token is not validation."),
("Flask context", "Which Flask proxy exposes the current request's headers and data?", "request", "request is a context-local proxy available during a request."),
("Flask JSON", "Return a JSON response from a Flask view.", "return jsonify({'ok': True})", "jsonify serializes the value and sets the response content type."),
("Flask route", "Restrict a Flask route to POST requests.", "@app.route('/submit', methods=['POST'])", "The methods option controls allowed HTTP verbs."),
("Environment config", "Why load Flask secrets from environment variables?", "They keep deployment-specific secrets out of source control.", "Environment configuration separates code from operational secrets."),
("Transaction", "How should a sqlite3 write be finalized?", "connection.commit()", "Commit makes the transaction durable."),
("Rollback", "Undo an uncommitted sqlite3 transaction after an error.", "connection.rollback()", "Rollback restores the state from before the transaction."),
("Foreign key", "How do you enable SQLite foreign key enforcement per connection?", "connection.execute('PRAGMA foreign_keys = ON')", "SQLite requires enabling foreign keys on each connection."),
("Index", "When should you add an index to a frequently filtered column?", "When the read benefit outweighs write and storage cost, based on query patterns.", "Indexes accelerate lookup but must be maintained."),
("N+1", "What is the N+1 query problem?", "One query loads parents, then one additional query runs per parent.", "Join, batch, or eager-load related data to reduce round trips."),
("Cache invalidation", "Why must a cache write strategy define invalidation?", "Stale cached values otherwise survive beyond the source-of-truth update.", "Freshness is part of the cache contract."),
("Retry", "What should a retry policy include for a transient network error?", "A bounded attempt count, timeout, exponential backoff, and jitter.", "Bounds and jitter prevent retry storms."),
("Idempotency", "Why use an idempotency key on a payment creation endpoint?", "Retries can return the original result without creating duplicate charges.", "The server records the key and its outcome."),
("Pagination", "Why prefer cursor pagination for a changing large dataset?", "A cursor avoids many offset skips and is more stable under inserts.", "The cursor represents a position in an ordered result."),
("Rate limiting", "What does a token bucket rate limiter control?", "Average request rate while allowing a bounded burst.", "Tokens refill at a fixed rate up to bucket capacity."),
("CORS", "What does CORS control in a browser?", "Which origins browser JavaScript may use for cross-origin requests.", "It is a browser policy, not an authentication mechanism."),
("CSRF", "What is a standard defense for cookie-authenticated state changes?", "Use an unpredictable CSRF token and validate it server-side.", "SameSite cookies add defense but do not replace all controls."),
("XSS", "What is the primary defense against reflected XSS in HTML output?", "Context-aware output escaping with a safe templating engine.", "Treat user content as data, not markup."),
("Open redirect", "How can a login redirect parameter avoid open redirects?", "Allow only local paths or an explicit origin allowlist.", "Never redirect to arbitrary user-provided URLs."),
("Path traversal", "How should a download endpoint prevent ../ traversal?", "Resolve the requested path and verify it remains under the intended directory.", "String prefix checks alone are insufficient."),
("Serialization", "Why validate JSON shape at an API boundary?", "It turns untrusted input into a known contract before business logic uses it.", "Validation prevents malformed or surprising values downstream."),
("Observability", "What are the three common pillars of observability?", "Logs, metrics, and traces.", "Together they show events, aggregate health, and request paths."),
("Health check", "What should a liveness check answer?", "Whether the process is running and able to serve basic requests.", "Deep dependency checks belong in readiness or a separate diagnostic."),
("Graceful shutdown", "What should a server do on graceful shutdown?", "Stop accepting work, finish bounded in-flight requests, close resources, then exit.", "This reduces dropped requests and corrupt state."),
("Schema migration", "Why should a migration be versioned and repeatable?", "Deployments need a known sequence from one schema state to the next.", "Ad hoc production edits are difficult to audit and reproduce."),
("Property test", "What does property-based testing generate?", "Many inputs to check general invariants rather than only examples.", "It can find edge cases humans did not enumerate."),
("Fuzzing", "What does fuzz testing seek in a parser?", "Unexpected crashes, hangs, or unsafe behavior on malformed inputs.", "Generated mutations explore a broad input space."),
("Type narrowing", "How can isinstance help a type checker?", "It narrows a union to the checked runtime type within the branch.", "The checker uses the guard as a flow fact."),
("Memory view", "What is a memoryview useful for?", "Accessing buffer data without copying it.", "It can expose slices of bytes-like storage efficiently."),
("Slots", "What tradeoff does __slots__ introduce?", "It can reduce per-instance memory but restrict dynamic attributes and complicate some features.", "Slots replace the normal instance dictionary for declared fields."),
("Weak reference", "When is weakref useful?", "When tracking an object without keeping it alive for garbage collection.", "The reference becomes invalid after collection."),
("Profiling", "Which standard module provides deterministic call profiling?", "cProfile", "It records function-call timing and call counts."),
("Benchmarking", "Why use timeit instead of a single time.time measurement?", "timeit repeats controlled snippets and reduces measurement noise.", "It is designed for small code timing comparisons."),
]


SQL_CONCEPTS = [
("SELECT", "Return every column from users.", "SELECT * FROM users;", "SELECT reads rows from a relation."),
("WHERE", "Return active users only.", "SELECT * FROM users WHERE active = TRUE;", "WHERE filters rows before projection."),
("ORDER BY", "Sort products from highest price to lowest.", "SELECT * FROM products ORDER BY price DESC;", "DESC reverses the default ascending order."),
("LIMIT", "Return the first 10 rows from events ordered newest first.", "SELECT * FROM events ORDER BY created_at DESC LIMIT 10;", "LIMIT bounds the result set."),
("DISTINCT", "Return each country only once from customers.", "SELECT DISTINCT country FROM customers;", "DISTINCT removes duplicate projected rows."),
("COUNT", "Count all rows in orders.", "SELECT COUNT(*) FROM orders;", "COUNT(*) counts rows including rows with null fields."),
("SUM", "Calculate total amount from payments.", "SELECT SUM(amount) FROM payments;", "SUM aggregates numeric values."),
("AVG", "Calculate average rating from reviews.", "SELECT AVG(rating) FROM reviews;", "AVG returns the arithmetic mean."),
("GROUP BY", "Count orders per customer_id.", "SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id;", "GROUP BY creates one aggregate row per group."),
("HAVING", "Keep customer groups with at least five orders.", "SELECT customer_id FROM orders GROUP BY customer_id HAVING COUNT(*) >= 5;", "HAVING filters groups after aggregation."),
("INNER JOIN", "Join orders to customers by customer_id.", "SELECT * FROM orders JOIN customers USING (customer_id);", "An inner join keeps matching rows."),
("LEFT JOIN", "Keep every customer, including those without orders.", "SELECT c.*, o.id AS order_id FROM customers c LEFT JOIN orders o ON o.customer_id = c.id;", "A left join preserves all left-side rows."),
("NULL", "Find users whose deleted_at has no value.", "SELECT * FROM users WHERE deleted_at IS NULL;", "NULL requires IS NULL rather than = NULL."),
("COALESCE", "Display 'Unknown' when nickname is null.", "SELECT COALESCE(nickname, 'Unknown') FROM users;", "COALESCE returns the first non-null expression."),
("CASE", "Label orders as big when total >= 100, otherwise small.", "SELECT CASE WHEN total >= 100 THEN 'big' ELSE 'small' END FROM orders;", "CASE expresses conditional SQL logic."),
("INSERT", "Insert a user named Ada with email ada@example.com.", "INSERT INTO users (name, email) VALUES ('Ada', 'ada@example.com');", "Explicit columns make inserts resilient to schema order."),
("UPDATE", "Mark order 7 as shipped.", "UPDATE orders SET status = 'shipped' WHERE id = 7;", "A precise WHERE clause prevents mass updates."),
("DELETE", "Delete expired sessions before a cutoff timestamp.", "DELETE FROM sessions WHERE expires_at < '2026-01-01';", "DELETE permanently removes matching rows."),
("PRIMARY KEY", "What constraint uniquely identifies each row?", "PRIMARY KEY", "A primary key is unique and non-null by definition."),
("FOREIGN KEY", "What constraint ensures order.customer_id references a customer?", "FOREIGN KEY (customer_id) REFERENCES customers(id)", "Foreign keys enforce referential integrity."),
("UNIQUE", "Prevent duplicate email values in users.", "UNIQUE (email)", "A unique constraint rejects duplicate non-null values."),
("CHECK", "Require account balance to be non-negative.", "CHECK (balance >= 0)", "CHECK rejects rows violating the expression."),
("CREATE TABLE", "Create notes with an integer id primary key and body text.", "CREATE TABLE notes (id INTEGER PRIMARY KEY, body TEXT NOT NULL);", "DDL defines the table and its constraints."),
("ALTER TABLE", "Add a timezone column to users.", "ALTER TABLE users ADD COLUMN timezone TEXT;", "ALTER TABLE changes an existing table definition."),
("DROP", "Remove a temporary table if it exists.", "DROP TABLE IF EXISTS temp_results;", "IF EXISTS makes absence non-fatal."),
("Index", "Create an index supporting user lookup by email.", "CREATE INDEX idx_users_email ON users(email);", "An index can speed predicates on its columns."),
("Composite index", "Index orders for queries filtering customer and sorting by date.", "CREATE INDEX idx_orders_customer_date ON orders(customer_id, created_at);", "Column order should match common predicates and ordering."),
("LIKE", "Find names beginning with 'Al'.", "SELECT * FROM users WHERE name LIKE 'Al%';", "% matches any sequence of characters."),
("IN", "Find tasks whose status is open or blocked.", "SELECT * FROM tasks WHERE status IN ('open', 'blocked');", "IN is concise equality against a value set."),
("BETWEEN", "Find invoices from 100 through 500 inclusive.", "SELECT * FROM invoices WHERE total BETWEEN 100 AND 500;", "BETWEEN includes both endpoints."),
("EXISTS", "Return customers who have at least one order.", "SELECT * FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);", "EXISTS stops after finding one matching row."),
("Subquery", "Find products priced above the average price.", "SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);", "The scalar subquery supplies the comparison value."),
("CTE", "Use a named query for monthly totals before selecting large months.", "WITH monthly AS (SELECT month, SUM(total) total FROM orders GROUP BY month) SELECT * FROM monthly WHERE total > 1000;", "A CTE makes a reusable query block readable."),
("Window function", "Show each employee salary alongside department average.", "SELECT name, salary, AVG(salary) OVER (PARTITION BY department_id) FROM employees;", "Window functions retain detail rows while computing group context."),
("ROW_NUMBER", "Number each user's orders newest first per user.", "ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC)", "ROW_NUMBER assigns a unique sequence within each partition."),
("RANK", "Rank products by sales while preserving ties.", "RANK() OVER (ORDER BY sales DESC)", "RANK gives tied rows the same rank and leaves gaps."),
("UNION", "Combine current and archived email lists, removing duplicates.", "SELECT email FROM current_users UNION SELECT email FROM archived_users;", "UNION removes duplicates between compatible result sets."),
("UNION ALL", "Combine logs while retaining duplicate rows.", "SELECT message FROM app_logs UNION ALL SELECT message FROM audit_logs;", "UNION ALL avoids duplicate elimination work."),
("INTERSECT", "Return IDs present in both table queries.", "SELECT id FROM a INTERSECT SELECT id FROM b;", "INTERSECT keeps values common to both sets."),
("EXCEPT", "Return IDs in a that are absent from b.", "SELECT id FROM a EXCEPT SELECT id FROM b;", "EXCEPT performs set difference."),
("Transaction", "Start a transaction, create an order, then make it durable.", "BEGIN; INSERT INTO orders (total) VALUES (25); COMMIT;", "A transaction groups changes into one unit."),
("ROLLBACK", "Undo the current transaction after a failed validation.", "ROLLBACK;", "Rollback discards uncommitted changes."),
("ACID", "What does the A in ACID stand for?", "Atomicity", "Atomicity means a transaction is all-or-nothing."),
("Isolation", "What does transaction isolation protect against?", "It controls how concurrent transactions can observe each other's intermediate changes.", "Isolation balances consistency and concurrency."),
("Deadlock", "Name one strategy for reducing database deadlocks.", "Acquire locks in a consistent order and keep transactions short.", "A global ordering reduces circular wait."),
("Normalization", "What is the goal of third normal form?", "Remove transitive dependencies so non-key columns depend on the key, the whole key, and nothing but the key.", "Normalization reduces update anomalies."),
("Denormalization", "When can denormalization be justified?", "When measured read performance or reporting needs outweigh the cost of maintaining redundant data.", "It should be deliberate and tested."),
("View", "Create a view exposing only public user columns.", "CREATE VIEW public_users AS SELECT id, name FROM users;", "A view stores a query as a reusable virtual relation."),
("Materialized view", "How does a materialized view differ from a normal view?", "It stores query results and must be refreshed.", "Stored results can improve read performance at freshness cost."),
("Trigger", "What database object runs automatically after a row change?", "A trigger", "Triggers attach procedural actions to table events."),
("Stored procedure", "What is a stored procedure?", "A named, database-resident program that can accept parameters and perform operations.", "It centralizes logic inside the database engine."),
("EXPLAIN", "Inspect a query's execution plan.", "EXPLAIN SELECT * FROM orders WHERE customer_id = 7;", "EXPLAIN reveals access paths and operators."),
("Query plan", "What does a sequential scan mean?", "The engine reads table rows one by one.", "It can be appropriate for small tables or broad predicates."),
("Sargability", "Why avoid applying a function to an indexed column in a WHERE clause?", "It may prevent the optimizer from using a normal index seek.", "Compare against a transformed parameter or use a functional index when supported."),
("Parameter binding", "How should an application pass a user-supplied ID to SQL?", "Use a bound parameter such as WHERE id = ?.", "Binding prevents the value from becoming SQL syntax."),
("SQL injection", "What vulnerability results from concatenating raw input into SQL?", "SQL injection", "Attackers can alter the intended query."),
("Collation", "What controls text comparison and sort rules?", "A collation", "Collations define language and case/ accent behavior."),
("Encoding", "Why store Unicode text using a database's supported Unicode type/encoding?", "To preserve characters across input, storage, and output.", "Mismatched encodings corrupt text."),
("Date interval", "Find events in the last 7 days in PostgreSQL-style SQL.", "WHERE created_at >= CURRENT_TIMESTAMP - INTERVAL '7 days'", "Interval arithmetic expresses a relative time boundary."),
("Date truncation", "Group timestamps by day in PostgreSQL.", "date_trunc('day', created_at)", "Truncation maps timestamps to a calendar boundary."),
("Time zones", "Why store event timestamps consistently in UTC?", "It gives a stable instant for comparison across regions.", "Convert to a user's zone only for presentation."),
("Upsert", "In PostgreSQL, insert an email or update its name on conflict.", "INSERT INTO users (email, name) VALUES ('a@x.test', 'A') ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name;", "An upsert combines insert and conflict update atomically."),
("MERGE", "What does SQL MERGE combine?", "Conditional insert, update, or delete based on matching source and target rows.", "It expresses synchronization logic declaratively."),
("Cascade", "What does ON DELETE CASCADE do to child rows?", "It deletes referencing child rows when the parent is deleted.", "Use it only when that ownership behavior is intended."),
("Restrict", "What does ON DELETE RESTRICT do?", "It prevents deleting a parent while referenced child rows exist.", "It forces the application to resolve dependencies explicitly."),
("Nullable unique", "Why can a UNIQUE column allow multiple NULLs in some databases?", "NULL represents an unknown value and is not equal to another NULL under common semantics.", "Exact NULL behavior is database-specific."),
("Partial index", "What is a partial index useful for?", "Indexing only rows matching a predicate, such as active records.", "It reduces index size for selective workloads."),
("Covering index", "What is a covering index?", "An index containing all columns needed by a query, allowing an index-only lookup.", "It can avoid table access when visibility rules permit."),
("Cardinality", "What does column cardinality describe?", "The number or distribution of distinct values.", "Cardinality helps optimizers estimate selectivity."),
("Selectivity", "What makes a predicate selective?", "It matches a small fraction of rows.", "Selective predicates often benefit more from indexes."),
("Replication", "What is read replication commonly used for?", "Scaling read traffic and improving availability with copies of data.", "Replication lag means reads may be stale."),
("Read-after-write", "What consistency requirement lets a user immediately see their own update?", "Read-your-writes consistency", "Routing to a primary or waiting for replication can provide it."),
("Sharding", "What is database sharding?", "Partitioning data across independent database nodes by a shard key.", "It scales capacity but complicates queries and operations."),
("Partitioning", "Why partition a large time-series table by date?", "To prune irrelevant partitions and simplify retention operations.", "Partitioning is not a substitute for every useful index."),
("Connection pool", "Why use a database connection pool?", "Reuse bounded connections and avoid connection setup per request.", "The pool must return connections cleanly after each use."),
("Prepared statement", "What is a prepared statement's key benefit?", "It separates a parsed SQL plan from bound values and improves safety.", "It may also reduce repeated parse cost."),
("Constraint", "Why enforce important invariants in the database as constraints?", "Every writer receives the guarantee, not only one application path.", "Database constraints protect the source of truth."),
("NULL aggregate", "What does SUM return for no matching non-null values in many SQL databases?", "NULL", "Use COALESCE(SUM(...), 0) when zero is the desired presentation."),
("COUNT column", "How does COUNT(email) differ from COUNT(*)?", "COUNT(email) excludes rows where email is NULL; COUNT(*) counts rows.", "The expression determines null handling."),
("Join duplication", "Why can a one-to-many join increase the number of result rows?", "Each parent row combines with every matching child row.", "Aggregate or use EXISTS when you only need parent existence."),
("Anti-join", "Return customers with no orders using NOT EXISTS.", "SELECT * FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);", "NOT EXISTS is a clear anti-join and handles nulls well."),
("Lateral join", "What does a lateral join allow a subquery to reference?", "Columns from preceding FROM items.", "It supports per-row derived calculations and top-N lookups."),
("Recursive CTE", "What query feature traverses a hierarchy from a starting row?", "A recursive CTE", "The anchor and recursive member repeatedly produce descendants."),
("Lock", "What does SELECT ... FOR UPDATE request?", "Row locks preventing conflicting updates until the transaction ends.", "Use it only inside an appropriate transaction."),
("Serializable", "What is the strongest standard transaction isolation level?", "SERIALIZABLE", "It provides behavior equivalent to serial execution, often with retries."),
("Migration", "What is a zero-downtime column migration pattern?", "Add nullable column, deploy compatible writers/readers, backfill, enforce constraint later.", "Expand-and-contract avoids incompatible deploy steps."),
("Backup", "Why test restoring database backups?", "A backup is useful only if it can be restored within recovery objectives.", "Restore drills reveal corruption and missing procedures."),
("RPO", "What does recovery point objective measure?", "The maximum acceptable amount of data loss measured in time.", "It guides backup and replication frequency."),
("RTO", "What does recovery time objective measure?", "The maximum acceptable time to restore service.", "It guides automation and standby capacity."),
]


VBA_CONCEPTS = [
("Variable declaration", "Declare a Long variable named rowNumber.", "Dim rowNumber As Long", "Explicit declarations catch misspellings and communicate intent."),
("Option Explicit", "What module statement requires variables to be declared?", "Option Explicit", "It prevents accidental implicit Variant variables."),
("Constant", "Declare a string constant named REPORT_SHEET with value Summary.", "Const REPORT_SHEET As String = \"Summary\"", "Constants make stable values clear and centralized."),
("Procedure", "Declare a public Sub named RefreshReport with no arguments.", "Public Sub RefreshReport()\nEnd Sub", "A Sub performs actions without returning a value."),
("Function", "Declare a function DoubleIt accepting a Double and returning Double.", "Function DoubleIt(value As Double) As Double\n    DoubleIt = value * 2\nEnd Function", "VBA assigns the return value to the function name."),
("If", "Set status to Ready when count is greater than zero.", "If count > 0 Then status = \"Ready\"", "If conditionally executes a statement."),
("If Else", "Set label to High for score >= 80, otherwise Low.", "If score >= 80 Then\n    label = \"High\"\nElse\n    label = \"Low\"\nEnd If", "Else handles the alternate branch."),
("Select Case", "Choose a message for status values Open and Closed.", "Select Case status\n    Case \"Open\": message = \"In progress\"\n    Case \"Closed\": message = \"Done\"\nEnd Select", "Select Case is readable for multiple alternatives."),
("For loop", "Loop row from 1 through 10.", "For row = 1 To 10\nNext row", "For is appropriate for a known numeric range."),
("For Each", "Iterate through every cell in rng.", "For Each cell In rng\nNext cell", "For Each visits members of a collection or range."),
("Do While", "Keep processing while moreData is True.", "Do While moreData\nLoop", "The condition is tested before each iteration."),
("Do Until", "Loop until isComplete becomes True.", "Do Until isComplete\nLoop", "The body runs while the terminating condition is false."),
("Array", "Declare a one-dimensional array of 100 Long values.", "Dim values(1 To 100) As Long", "The bounds define valid array indexes."),
("Dynamic array", "Declare a resizable string array and resize it to 20 items.", "Dim names() As String\nReDim names(1 To 20)", "ReDim allocates a dynamic array."),
("Preserve", "Resize values to 200 while retaining existing elements.", "ReDim Preserve values(1 To 200)", "Preserve copies existing values during resize."),
("Range value", "Read cell A1 on Sheet1 into a variable.", "value = Worksheets(\"Sheet1\").Range(\"A1\").Value", "Fully qualifying the worksheet avoids active-sheet dependence."),
("Range write", "Write total to B2 on the Reports worksheet.", "Worksheets(\"Reports\").Range(\"B2\").Value = total", "Value assigns the cell's underlying content."),
("Cells", "Reference row 5, column 3 on the active sheet.", "Cells(5, 3)", "Cells uses numeric row and column indexes."),
("With block", "Set font bold and interior color for rng using one object reference.", "With rng\n    .Font.Bold = True\n    .Interior.Color = vbYellow\nEnd With", "With reduces repeated qualification."),
("Worksheet", "Get the worksheet named Data from ThisWorkbook.", "ThisWorkbook.Worksheets(\"Data\")", "ThisWorkbook means the workbook containing the code."),
("Workbook", "Open a workbook at the supplied file path.", "Workbooks.Open filePath", "Open returns a Workbook object."),
("Last row", "Find the last used row in column A of ws.", "ws.Cells(ws.Rows.Count, 1).End(xlUp).Row", "Starting at the bottom and moving up finds the last populated cell."),
("Range resize", "Create a range starting at A1 with 10 rows and 3 columns.", "ws.Range(\"A1\").Resize(10, 3)", "Resize changes range dimensions from its anchor."),
("Value2", "Why can Value2 be preferred for bulk Excel reads?", "It avoids Currency and Date subtype conversions.", "Value2 returns raw values with fewer implicit conversions."),
("Bulk read", "Read a rectangular range into a Variant array.", "data = ws.Range(\"A1:C100\").Value2", "One COM transfer is much faster than cell-by-cell reads."),
("Bulk write", "Write a 2D Variant array to a same-sized range.", "ws.Range(\"A1:C100\").Value2 = data", "Bulk assignment minimizes Excel object-model calls."),
("MsgBox", "Display an informational message saying Complete.", "MsgBox \"Complete\", vbInformation", "MsgBox presents a standard dialog."),
("InputBox", "Prompt the user for a project name.", "projectName = InputBox(\"Project name:\")", "InputBox returns entered text or an empty string."),
("Error handler", "Start a procedure error handler that jumps to HandleError.", "On Error GoTo HandleError", "Errors transfer control to the labeled handler."),
("Cleanup", "What block should release Excel state after an error handler?", "A cleanup section that restores settings before Exit Sub.", "State restoration must happen on success and failure."),
("Err object", "Read the current VBA error number.", "Err.Number", "Err exposes information about the most recent error."),
("Raise", "Raise a custom runtime error with number  vbObjectError + 100.", "Err.Raise vbObjectError + 100, , \"Invalid input\"", "Err.Raise creates a controlled error for callers."),
("Resume", "Continue at the statement after the one that failed.", "Resume Next", "Resume Next is appropriate only when the error is safely handled."),
("Object variable", "Declare a worksheet object variable.", "Dim ws As Worksheet", "Object variables hold references to Excel objects."),
("Set", "Assign the Data worksheet object to ws.", "Set ws = ThisWorkbook.Worksheets(\"Data\")", "Set is required when assigning object references."),
("Nothing", "Test whether ws has no object reference.", "If ws Is Nothing Then", "Is Nothing tests object reference state."),
("Early binding", "What is an advantage of declaring Dim app As Excel.Application?", "Compile-time member checking and IntelliSense.", "It requires an available referenced library."),
("Late binding", "Create Excel.Application without a compile-time reference.", "Set app = CreateObject(\"Excel.Application\")", "Late binding improves deployment independence but loses compile-time typing."),
("Object cleanup", "Release a workbook object reference.", "Set wb = Nothing", "Clearing references helps release COM objects."),
("ScreenUpdating", "Disable screen redraw during a controlled macro operation.", "Application.ScreenUpdating = False", "Reducing redraw can improve performance; restore it afterward."),
("Calculation", "Temporarily set Excel calculation to manual.", "Application.Calculation = xlCalculationManual", "Manual calculation avoids repeated recalculation during bulk changes."),
("EnableEvents", "Why restore Application.EnableEvents after a macro?", "Leaving events disabled can silently break later workbook automation.", "Application state is shared and must be restored."),
("Protect", "Protect the active worksheet with a password.", "ActiveSheet.Protect Password:=password", "Protection restricts edits according to configured options."),
("Unprotect", "Remove protection from ws with a password.", "ws.Unprotect Password:=password", "The password must match the protection configuration."),
("AutoFilter", "Filter table field 2 for the value Open.", "table.Range.AutoFilter Field:=2, Criteria1:=\"Open\"", "AutoFilter applies criteria to a range or table."),
("ListObject", "Get the Excel table named Sales.", "Set table = ws.ListObjects(\"Sales\")", "ListObjects represent structured Excel tables."),
("ListColumn", "Reference the Amount column in table.", "table.ListColumns(\"Amount\").DataBodyRange", "DataBodyRange excludes the header row."),
("Named range", "Read a workbook-level named range called TaxRate.", "value = ThisWorkbook.Names(\"TaxRate\").RefersToRange.Value2", "Names provides defined-name objects."),
("Formula", "Set A1 to a SUM formula for A2:A10.", "ws.Range(\"A1\").Formula = \"=SUM(A2:A10)\"", "Formula writes an A1-style formula."),
("FormulaR1C1", "Set a formula in B2 summing the two cells to its left.", "ws.Range(\"B2\").FormulaR1C1 = \"=SUM(RC[-2]:RC[-1])\"", "R1C1 expresses references relative to the formula cell."),
("Number format", "Format a range as a percentage with two decimal places.", "rng.NumberFormat = \"0.00%\"", "NumberFormat controls display, not underlying value."),
("Interior", "Set rng's fill color to yellow.", "rng.Interior.Color = vbYellow", "Interior controls cell fill formatting."),
("Font", "Make rng's text bold.", "rng.Font.Bold = True", "Font exposes typography properties."),
("ClearContents", "Remove values from rng while retaining formatting.", "rng.ClearContents", "ClearContents leaves formats and comments intact."),
("ClearFormats", "Remove formatting from rng while retaining values.", "rng.ClearFormats", "ClearFormats affects presentation only."),
("Copy", "Copy A1:B2 to D1.", "ws.Range(\"A1:B2\").Copy Destination:=ws.Range(\"D1\")", "Destination avoids clipboard interaction."),
("PasteSpecial", "Paste only values from copied range.", "target.PasteSpecial Paste:=xlPasteValues", "PasteSpecial selects a specific clipboard component."),
("Find", "Find the first cell containing the exact text Open.", "Set hit = rng.Find(What:=\"Open\", LookAt:=xlWhole)", "Specify Find arguments to avoid remembered UI settings."),
("Find next", "What must a looping Find call remember to avoid cycling forever?", "The first found address.", "Stop when FindNext returns to the first address."),
("Sort", "What object provides sorting for an Excel range?", "The range's Sort method or a Sort object.", "Sorting should explicitly specify key and order."),
("Collection", "Add an item to a VBA Collection.", "items.Add item", "Collection maintains ordered items and optional keys."),
("Dictionary", "Create a late-bound Scripting.Dictionary.", "Set dict = CreateObject(\"Scripting.Dictionary\")", "A dictionary provides key-based lookup."),
("Dictionary exists", "Test whether dict contains key email.", "If dict.Exists(email) Then", "Exists avoids an error from missing-key access."),
("Dictionary compare", "Make dictionary keys case-insensitive.", "dict.CompareMode = vbTextCompare", "CompareMode should be set before adding keys."),
("String length", "Get the number of characters in text.", "Len(text)", "Len returns character count."),
("Trim", "Remove leading and trailing spaces from input.", "Trim$(inputText)", "Trim$ returns a String and strips outer spaces."),
("Replace", "Replace every comma in text with a semicolon.", "Replace(text, \",\", \";\")", "Replace returns a transformed string."),
("InStr", "Find the first occurrence of @ in email.", "InStr(1, email, \"@\", vbTextCompare)", "InStr returns the one-based position or zero."),
("Split", "Split CSV text into an array using commas.", "parts = Split(csv, \",\")", "Split separates text at a delimiter."),
("Join", "Join a string array with a comma and space.", "csv = Join(parts, \", \")", "Join combines array elements."),
("Convert", "Convert a text number into a Long.", "CLng(textNumber)", "Conversion functions make intended type coercion explicit."),
("Date", "Get today's date without the time.", "Date", "Date is VBA's built-in current date value."),
("DateAdd", "Add 7 days to startDate.", "DateAdd(\"d\", 7, startDate)", "DateAdd handles date intervals."),
("DateDiff", "Calculate days between startDate and endDate.", "DateDiff(\"d\", startDate, endDate)", "DateDiff returns the number of interval boundaries."),
("Format", "Format amount as currency.", "Format(amount, \"$#,##0.00\")", "Format returns display text."),
("Boolean", "What values represent True and False in VBA?", "True is -1 and False is 0.", "VBA Boolean values have numeric representations."),
("ByVal", "What does ByVal mean for a procedure parameter?", "The procedure receives a copy of the value or reference pointer.", "Assignments to the parameter do not reassign the caller's variable."),
("ByRef", "What does ByRef permit?", "The procedure can modify the caller's variable through the reference.", "ByRef is the default parameter passing mode."),
("Optional", "Declare an optional Boolean parameter named verbose defaulting False.", "Optional verbose As Boolean = False", "Optional parameters allow callers to omit an argument."),
("ParamArray", "What keyword accepts a variable number of arguments?", "ParamArray", "ParamArray must be the final parameter and is an array."),
("Enum", "Declare an enum Priority with Low and High members.", "Enum Priority\n    Low\n    High\nEnd Enum", "Enums give related numeric constants meaningful names."),
("Type", "What legacy VBA construct groups related fields?", "Type ... End Type", "A user-defined Type groups fixed fields."),
("Class module", "Where should reusable object behavior be implemented in VBA?", "A class module with Private fields and Public methods/properties.", "Class modules encapsulate state and behavior."),
("Property Get", "What procedure reads a class property?", "Property Get", "Property Get defines read behavior."),
("Property Let", "What procedure assigns a value-type class property?", "Property Let", "Property Let handles assignment of non-object values."),
("Property Set", "What procedure assigns an object property?", "Property Set", "Property Set handles object references."),
("Event", "What keyword declares a class event?", "Event", "RaiseEvent signals subscribers to an event."),
("WithEvents", "What declaration receives events from an object?", "Private WithEvents app As Application", "WithEvents enables event procedure handlers."),
("DoEvents", "What does DoEvents allow during a long macro?", "It yields execution so Windows and pending events can be processed.", "Use sparingly because reentrancy can complicate state."),
("Performance", "What is the main performance rule for large Excel data operations?", "Read and write rectangular ranges in arrays rather than looping through cells.", "Crossing the Excel COM boundary per cell is expensive."),
("Security", "Why should macros validate workbook paths and external inputs?", "Untrusted paths and commands can expose or modify unintended files.", "Treat workbook content as untrusted input."),
("Macro signing", "What does signing a VBA project help users verify?", "The publisher identity and whether the project changed after signing.", "Signing does not make unsafe code safe by itself."),
("Workbook events", "Which event runs when a workbook is opened?", "Workbook_Open", "It is implemented in the ThisWorkbook module."),
("Sheet event", "Which event runs when a worksheet cell changes?", "Worksheet_Change", "It receives the changed Range as a parameter."),
("Intersect", "Check whether changed intersects monitored range.", "If Not Intersect(Target, monitored) Is Nothing Then", "Intersect returns overlapping cells or Nothing."),
("Cancel event", "How can BeforeClose prevent closing?", "Set Cancel = True", "Cancel event arguments let handlers veto an action."),
("Debug", "Print a diagnostic value to the Immediate window.", "Debug.Print value", "Debug.Print is useful for local VBA diagnostics."),
("Breakpoints", "What does a VBA breakpoint do?", "It pauses execution at a selected line for inspection.", "Breakpoints support step-through debugging."),
("Immediate window", "Which window evaluates VBA expressions interactively?", "The Immediate window", "It is opened from the VBA editor's View menu."),
("Watch", "What is a watch expression used for?", "Pausing or inspecting execution when an expression changes or meets a condition.", "Watches expose changing state during debugging."),
("Testability", "How can a macro be made easier to test?", "Separate pure transformations from Excel I/O and pass dependencies explicitly.", "Small deterministic procedures are easier to verify."),
("Cleanup pattern", "What is the safest broad structure for restoring Excel state?", "Capture state, set temporary state, use one cleanup path, restore captured values.", "Restoration must run on both normal and error exits."),
]


SQL_EXTRA = [
    ("Functional dependency", "What does a functional dependency X -> Y mean?", "Each X value determines exactly one Y value.", "Functional dependencies guide normalization and key design."),
    ("Candidate key", "What is a candidate key?", "A minimal set of columns that uniquely identifies a row.", "A table may have multiple candidate keys; one is chosen as primary."),
    ("Surrogate key", "What is a surrogate key?", "A generated identifier with no business meaning.", "Surrogate keys decouple relationships from changeable business values."),
    ("Natural key", "What is a natural key?", "A real-world attribute or combination that uniquely identifies a row.", "Natural keys can be meaningful but may change or be wide."),
    ("Null-safe equality", "How can PostgreSQL compare two values treating two NULLs as equal?", "a IS NOT DISTINCT FROM b", "This operator defines NULL-safe equality."),
    ("JSON extraction", "In PostgreSQL, extract the name text from a JSONB document profile.", "profile->>'name'", "The ->> operator extracts a JSON value as text."),
    ("Array unnest", "Expand a PostgreSQL integer array into rows.", "SELECT unnest(values);", "unnest turns array elements into a result set."),
    ("Full-text search", "What database feature supports token-aware document search?", "A full-text search index and query configuration.", "Tokenization and ranking are more suitable than broad wildcard scans."),
    ("Temporal integrity", "How can a database prevent overlapping bookings for one room?", "Use an exclusion constraint or a transactionally enforced overlap check.", "The invariant must be protected against concurrent inserts."),
    ("Audit trail", "What should an audit record capture for a sensitive change?", "Actor, action, target, timestamp, and relevant before/after context.", "Audit data should be append-oriented and access controlled."),
    ("Online index", "Why create a large production index using an online/concurrent option when supported?", "It reduces blocking of normal reads and writes during index construction.", "The exact locking and transaction rules depend on the database."),
]


QUESTIONS = (_make_questions("python", PYTHON_CONCEPTS[:100])
             + _make_questions("sql", (SQL_CONCEPTS + SQL_EXTRA)[:100])
             + _make_questions("vba", VBA_CONCEPTS[:100]))

BEGINNER_EXERCISES = {
    "List comprehension": {
        "prompt": "Write a function that returns the squares of even numbers in nums.",
        "examples": [{"input": "nums = [1, 2, 3, 4, 5, 6]", "output": "[4, 16, 36]"}, {"input": "nums = [7, 9]", "output": "[]"}],
        "starter_code": "def even_squares(nums):\n    # Write your solution here\n    pass",
        "solution_code": "def even_squares(nums):\n    return [number ** 2 for number in nums if number % 2 == 0]",
        "test_cases": [{"args": [[1, 2, 3, 4, 5, 6]], "expected": [4, 16, 36]}, {"args": [[7, 9]], "expected": []}],
        "hints": ["Look at each number one at a time.", "Use a loop and an if condition, then square values that pass.", "Pseudocode: create an empty result; for each number, if it is even, append its square."],
        "tags": ["lists", "loops", "conditions"], "function_name": "even_squares",
    },
    "Dictionary counting": {
        "prompt": "Write a function that returns how many times each value appears in values.",
        "examples": [{"input": "values = ['a', 'b', 'a', 'c', 'b', 'a']", "output": "{'a': 3, 'b': 2, 'c': 1}"}],
        "starter_code": "def count_values(values):\n    # Write your solution here\n    pass",
        "solution_code": "def count_values(values):\n    counts = {}\n    for value in values:\n        counts[value] = counts.get(value, 0) + 1\n    return counts",
        "test_cases": [{"args": [["a", "b", "a", "c", "b", "a"]], "expected": {"a": 3, "b": 2, "c": 1}}, {"args": [[]], "expected": {}}],
        "hints": ["Keep one running total for each distinct value.", "A dictionary can map a value to its current count.", "For each value, read its old count or zero, add one, then return the dictionary."],
        "tags": ["dictionaries", "loops", "counting"], "function_name": "count_values",
    },
    "Safe dictionary lookup": {
        "prompt": "Write a function that returns the value for key from settings, or default when key is absent.",
        "examples": [{"input": "settings = {'mode': 'test'}, key = 'timeout', default = 30", "output": "30"}],
        "starter_code": "def get_setting(settings, key, default):\n    # Write your solution here\n    pass",
        "solution_code": "def get_setting(settings, key, default):\n    return settings.get(key, default)",
        "test_cases": [{"args": [{"mode": "test"}, "timeout", 30], "expected": 30}, {"args": [{"mode": "test"}, "mode", "dev"], "expected": "test"}],
        "hints": ["Dictionaries have a method for a lookup with a fallback.", "The fallback should only be used when the key is missing.", "Use settings.get with key and default."],
        "tags": ["dictionaries", "functions"], "function_name": "get_setting",
    },
    "Tuple unpacking": {
        "prompt": "Write a function that returns values with the first and last items swapped.",
        "examples": [{"input": "values = [1, 2, 3, 4]", "output": "[4, 2, 3, 1]"}],
        "starter_code": "def swap_ends(values):\n    # Write your solution here\n    pass",
        "solution_code": "def swap_ends(values):\n    result = values.copy()\n    result[0], result[-1] = result[-1], result[0]\n    return result",
        "test_cases": [{"args": [[1, 2, 3, 4]], "expected": [4, 2, 3, 1]}, {"args": [[9, 2]], "expected": [2, 9]}],
        "hints": ["Make a copy so the original list stays unchanged.", "Indexes 0 and -1 refer to the first and last items.", "Assign both indexed values in one statement."],
        "tags": ["lists", "indexes", "functions"], "function_name": "swap_ends",
    },
    "Generator expression": {
        "prompt": "Write a function that returns a list of non-empty lines after stripping whitespace.",
        "examples": [{"input": "lines = [' one ', '', ' two']", "output": "['one', 'two']"}],
        "starter_code": "def clean_lines(lines):\n    # Write your solution here\n    pass",
        "solution_code": "def clean_lines(lines):\n    return [line.strip() for line in lines if line.strip()]",
        "test_cases": [{"args": [[" one ", "", " two"]], "expected": ["one", "two"]}, {"args": [["  ", "ok"]], "expected": ["ok"]}],
        "hints": ["Each line needs two decisions: clean it, then check whether it has content.", "Use strip() and a condition in a loop or comprehension.", "Strip first and include the result only when the stripped text is non-empty."],
        "tags": ["lists", "strings", "conditions"], "function_name": "clean_lines",
    },
}

for question in QUESTIONS:
    exercise = BEGINNER_EXERCISES.get(question["title"])
    if exercise:
        question.update(exercise)
    else:
        question.update({
            "examples": [], "starter_code": "", "solution_code": question["answer"],
            "test_cases": [], "hints": ["Break the task into one small step at a time."],
            "tags": [question["section"], question["difficulty"]], "function_name": "",
        })

assert len(QUESTIONS) == 300
assert all(sum(q["section"] == section and q["difficulty"] == level for q in QUESTIONS) == count
           for section in ("python", "sql", "vba")
           for level, count in (("easy", 50), ("medium", 30), ("hard", 20)))
